name: Notify Main Repository

on:
  push:
    branches:
      - main  

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Main Repository Workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.DEPLOY_PAT }}" \
          https://api.github.com/repos/danielrosehill/Documentation-Root-Repo/actions/workflows/pull-and-build.yml/dispatches \
          -d '{"ref":"main"}' || echo "Failed to trigger main repository workflow"