name: Notify Main Repository

on:
  push:
    branches:
      - main  

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to main repo
        env:
          PAT: ${{ secrets.DEPLOY_PAT }}
        run: |
          curl -X POST \
            -H "Authorization: token $PAT" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/danielrosehill/Documetation-Root-Repo/dispatches \
            -d '{"event_type": "update_from_feeder", "client_payload": {"branch": "published"}}'