name: Notify Main Repository

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Main Repository Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DEPLOY_PAT }}
          repository: danielrosehill/Documentation-Root-Repo
          event-type: feeder-updated
          client-payload: '{"feeder": "${{ github.repository }}"}'